services:
  db:
    image: postgres:18-alpine
    container_name: booking-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - booking-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: booking-api
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
    booking-data: